# -------
# Library
# -------

library:
  name: Lumberjack
  api: 21
  github: MFlisar/Lumberjack
  maven: io.github.mflisar.lumberjack
  maven-main-library: core
  multiplatform: true
  platforms:
    - android
    - ios
    - windows
    - macos
    - wasm
  screenshots: 
    - name: core
      images:
        - ./screenshots/core/log1.png
        - ./screenshots/core/log2.png
    - name: composeviewer
      images:
        - ./screenshots/composeviewer/compose-viewer1.jpg
        - ./screenshots/composeviewer/compose-viewer2.jpg
    - name: viewer
      images:
        - ./screenshots/viewer/viewer1.jpg
        - ./screenshots/viewer/viewer2.jpg
  branch: master
  demo: true

# ------------
# Dependencies
# ------------

dependencies:
  compose-multiplatform: 1.8.1 # https://github.com/JetBrains/compose-multiplatform/releases
  jetpack-compose-runtime: 1.8.1 # https://developer.android.com/jetpack/androidx/releases/compose-runtime
  jetpack-compose-material3: 1.3.2 # https://developer.android.com/jetpack/androidx/releases/compose-material3
  experimental: true

# ------------
# Groups
# ------------

groups:
  - name: core
    label: Core
    gradle-comment: core
  - name: lumberjack
    label: Lumberjack
    gradle-comment: if you want to use the lumberjack logger
  - name: extensions
    label: Extensions
    gradle-comment: extensions that work with any implementation
  - name: timber
    label: Timber
    gradle-comment: if you want to use the timber logger

# ------------
# Modules
# ------------

modules:
  - name: core
    group: core
    description: the core module of lumberjack
    optional: false
    platforms:
      - android
      - ios
      - windows
      - macos
      - wasm
    platforms-info: ""
    dependencies: []
  - name: extension-composeviewer
    group: extensions
    description: a compose viewer for lumberjack
    optional: true
    platforms:
      - android
      - ios
      - windows
      - macos
    platforms-info: ""
    dependencies:
      - name: FeedbackManager
        link: https://github.com/MFlisar/FeedbackManager
        version: 2.1.0
  - name: extension-feedback
    group: extensions
    description: a feedback module for lumberjack
    optional: true
    platforms:
      - android
    platforms-info: (1)
    dependencies:
      - name: FeedbackManager
        link: https://github.com/MFlisar/FeedbackManager
        version: 2.1.0
  - name: extension-notification
    group: extensions
    description: a notification module for lumberjack
    optional: true
    platforms:
      - android
    platforms-info: (1)
    dependencies:
      - name: FeedbackManager
        link: https://github.com/MFlisar/FeedbackManager
        version: 2.1.0
  - name: extension-viewer
    group: extensions
    description: a xml viewer for lumberjack
    optional: true
    platforms:
      - android
    platforms-info: (2)
    dependencies:
      - name: FeedbackManager
        link: https://github.com/MFlisar/FeedbackManager
        version: 2.1.0
      - name: FastScroller
        link: https://github.com/quiph/RecyclerView-FastScroller
        version: 1.0.0
  - name: implementation-lumberjack
    group: lumberjack
    description: the core lumberjack implementation
    optional: true
    platforms:
      - android
      - ios
      - windows
      - macos
      - wasm
    platforms-info: ""
    dependencies: []
  - name: implementation-timber
    group: timber
    description: the core timber based implementation of lumberjack
    optional: true
    platforms:
      - android
    platforms-info: (3)
    dependencies:
      - name: Timber
        link: https://github.com/JakeWharton/timber
        version: 4.7.1
  - name: logger-console
    group: lumberjack
    description: a console logger for lumberjack
    optional: true
    platforms:
      - android
      - ios
      - windows
      - macos
      - wasm
    platforms-info: ""
    dependencies: []
  - name: logger-file
    group: lumberjack
    description: a file logger for lumberjack
    optional: true
    platforms:
      - android
      - ios
      - windows
      - macos
    platforms-info: ""
    dependencies: []
  - name: logger-timber-console
    group: timber
    description: a console logger for the lumberjack timber implementation
    optional: true
    platforms:
      - android
    platforms-info: (3)
    dependencies:
      - name: Timber
        link: https://github.com/JakeWharton/timber
        version: 4.7.1
  - name: logger-timber-file
    group: timber
    description: a file logger for the lumberjack timber implementation
    optional: true
    platforms:
      - android
    platforms-info: (3)
    dependencies:
      - name: Timber
        link: https://github.com/JakeWharton/timber
        version: 4.7.1
      - name: slf4j
        link: https://www.slf4j.org/
        version: 2.0.7
      - name: logback-android
        link: https://github.com/tony19/logback-android
        version: 3.0.0