name: Android Build

on:
  workflow_dispatch:
#  push:
#    branches:
#      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      # 1) Checkout
      - uses: actions/checkout@v3
      
      # 2) Setup JAVA
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 3) gradlew permissions
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4) build debug apk
      - name: Build with Gradle
        run: ./gradlew assembleDebug --stacktrace

      # 5) upload debug apk
      - name: Upload APK Build Artifact
        uses: actions/upload-artifact@master
        with:
          name: demo
          path: demo/outputs/apk/debug/demo-debug.apk

