name: Publish
on:
  release:
    types: [published]

env:
  TAG: ${{ github.event.release.tag_name }}

jobs:

  build-on-macos:
      name: Build on macOS
      runs-on: macos-latest

      steps:

        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v4

        #- name: Build with Gradle
        #  run: ./gradlew build

        - name: Build with Gradle and publish to local maven repository
          run: ./gradlew publishToMavenLocal

        - name: Upload Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: publish-artifacts
            path: ~/.m2/repository

  publish:
    name: Publish to Maven Central
    runs-on: ubuntu-latest
    needs: [build-on-macos]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: publish-artifacts
          path: ~/.m2/repository

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish Library
        run: |
          echo "TAG: $TAG"
          echo "Publishing library 🚀"
          echo ""
          ./gradlew publish --no-build --no-daemon --no-parallel
          echo "Published✅"

        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}